### ISSUE TITLE
AttributeError: 'Iterator' object has no attribute '_output_classes'

### ISSUE THREAD

**Issue by jamesmgg** [jfkirk/tensorrec#66]
```
dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow in /Users/jguajardo/Library/Python/2.7/lib/python/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so being ignored in restricted program because it is a relative path
Generating positive interactions
Generating negative interactions
Generating user features
Generating item features
2018-05-21 20:52:17.596472: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
/Users/jguajardo/Library/Python/2.7/lib/python/site-packages/tensorflow/python/ops/gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Traceback (most recent call last):
  File "rec.py", line 15, in <module>
    model.fit(interactions, user_features, item_features, epochs=5, verbose=True)
  File "/Users/jguajardo/Library/Python/2.7/lib/python/site-packages/tensorrec/tensorrec.py", line 533, in fit
    n_sampled_items=n_sampled_items)
  File "/Users/jguajardo/Library/Python/2.7/lib/python/site-packages/tensorrec/tensorrec.py", line 601, in fit_partial
    self._build_tf_graph(n_user_features=n_user_features, n_item_features=n_item_features)
  File "/Users/jguajardo/Library/Python/2.7/lib/python/site-packages/tensorrec/tensorrec.py", line 488, in _build_tf_graph
    self._record_graph_hook_names()
  File "/Users/jguajardo/Library/Python/2.7/lib/python/site-packages/tensorrec/tensorrec.py", line 171, in _record_graph_hook_names
    output_classes = hook._output_classes
AttributeError: 'Iterator' object has no attribute '_output_classes'
```

Is this some weirdness happening because I'm running this on Python 2.7.10?

**Comment by jfkirk** [comment]
Hey @jamesmgg -- this issue is a result of a TensorFlow version mismatch. TensorRec was built on TensorFlow 1.7.0. Try updating your TF version and this error should go away.

Closing for now. If this issue persists, please re-open it.

**Comment by skylacking004** [comment]
Hey James, great program. I am having the same error Would I have to then downgrade tensorflow to 1.7.0?: 

> Loading ratings
Raw ratings example:
['userId', 'movieId', 'rating', 'timestamp']
[0, 0, 4.0, '964982703']
80668 train ratings, 20168 test ratings
Training collaborative filter
2019-02-22 08:54:14.956117: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/ops/gradients_impl.py:110: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Traceback (most recent call last):
  File "/tensorrec-master/examples/getting_started.py", line 65, in <module>
    item_features=item_indicator_features)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorrec/tensorrec.py", line 537, in fit
    n_sampled_items=n_sampled_items)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorrec/tensorrec.py", line 605, in fit_partial
    self._build_tf_graph(n_user_features=n_user_features, n_item_features=n_item_features)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorrec/tensorrec.py", line 492, in _build_tf_graph
    self._record_graph_hook_names()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorrec/tensorrec.py", line 178, in _record_graph_hook_names
    output_types = hook._output_types
AttributeError: 'Iterator' object has no attribute '_output_types'

>

**Comment by yun-zhou-rb** [comment]
In tensorrec.py around line 175, this change should make the code work on Tensorflow 1.14.0
```
        for graph_iterator_hook_attr_name in self.graph_iterator_hook_attr_names:
            hook = self.__getattribute__(graph_iterator_hook_attr_name)
            iterator_resource_name = hook._iterator_resource.name
            # output_types = hook._output_types
            # output_shapes = hook._output_shapes
            # output_classes = hook._output_classes
            output_types = tf.data.get_output_types(hook)
            output_shapes = tf.data.get_output_shapes(hook)
            output_classes = tf.data.get_output_classes(hook)
```
